# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0002_country_iso_code'),
        ('protected_areas', '0002_auto_20160105_2337'),
        ('core', '0035_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtiCity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('boundaries.city',),
        ),
        migrations.CreateModel(
            name='CtiCountry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('boundaries.country',),
        ),
        migrations.CreateModel(
            name='CtiProtectedArea',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('protected_areas.baseprotectedarea',),
        ),
        migrations.CreateModel(
            name='CtiState',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('boundaries.state',),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='permission_groups',
            field=models.ManyToManyField(related_name='permission_groups', to='auth.Group'),
        ),
    ]
