# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180412_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalProcedings',
            new_name='LegalProceedings',
        ),
        migrations.AlterModelOptions(
            name='legalproceedings',
            options={'verbose_name': 'Legal Proceeding', 'verbose_name_plural': 'Legal Proceedings'},
        ),
    ]
