# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180412_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='permission_groups',
            field=models.ManyToManyField(related_name='permission_groups', to='auth.Group', verbose_name='Permission Groups-'),
        ),
    ]
