# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 22:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180412_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indigenousland',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Acrescente a documentação oficial sobre a terra indígena (decretos de homologação, portarias declaratórias,etc.).\n                     Caso o mesmo documento se refira a mais de uma terra indígena, ele pode já estar cadastrado e você pode apenas selecioná-lo.\n                     Confira na lista antes de adicionar. ', related_name='indigenousland_documentation', to='core.Document', verbose_name='documentation'),
        ),
        migrations.AlterField(
            model_name='indigenousland',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Inclua aqui o polígono da terra indígena apenas em formato *.KML.\n                                        Certifique-se de que apenas a terra indígena correspondente está no arquivo. ', srid=4326, verbose_name='Indigenous Land Spatial Data'),
        ),
        migrations.AlterField(
            model_name='indigenousland',
            name='guarani_exclusive_possession_area_portion',
            field=models.FloatField(blank=True, help_text='Em caso de terras ainda em processo de regularização, caso tenha informação de qual porção da área já foi desintrusada incluir.\n                     Em áreas em que não se iniciou o processo de desintrusão colocar 0.', null=True, verbose_name='Guarani full and exclusive portion area possession'),
        ),
        migrations.AlterField(
            model_name='indigenousland',
            name='others_exclusive_possession_area_portion',
            field=models.FloatField(blank=True, help_text='Em caso de terras ainda em processo de regularização, caso tenha informação de qual porção da área já foi desintrusada incluir.\n                     Em áreas em que não se iniciou o processo de desintrusão colocar 0. ', null=True, verbose_name="Other peoples' full and exclusive portion area possession"),
        ),
        migrations.AlterField(
            model_name='indigenousland',
            name='prominent_subgroup',
            field=models.ManyToManyField(blank=True, related_name='indigenousland_prominent_subgroup_layers', to='core.ProminentEthnicSubGroup', verbose_name='Guarani ethnic sub-group'),
        ),
        migrations.AlterField(
            model_name='indigenousvillage',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Localize o ponto da aldeia.\n                                              Você pode incluir as coordenadas geográficas (em graus decimais) ou\n                                              localizar o ponto olhando o mapa ou a foto aérea do Google.', srid=4326, verbose_name='Geometry'),
        ),
        migrations.AlterField(
            model_name='indigenousvillage',
            name='prominent_subgroup',
            field=models.ManyToManyField(blank=True, related_name='indigenousvillage_prominent_subgroup_layers', to='core.ProminentEthnicSubGroup', verbose_name='Guarani ethnic sub-group'),
        ),
    ]
