# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0005_auto_20180501_2240'),
        ('core', '0040_auto_20180501_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeologicalplace',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='archaeologicalplace_ethnic_groups_layers', to='boundaries.City', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='archaeologicalplace',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archaeologicalplace_ethnic_groups_layers', to='boundaries.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='archaeologicalplace',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='archaeologicalplace_ethnic_groups_layers', to='boundaries.State', verbose_name='States'),
        ),
        migrations.AddField(
            model_name='indigenousland',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='indigenousland_ethnic_groups_layers', to='boundaries.City', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='indigenousland',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indigenousland_ethnic_groups_layers', to='boundaries.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='indigenousland',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='indigenousland_ethnic_groups_layers', to='boundaries.State', verbose_name='States'),
        ),
        migrations.AddField(
            model_name='indigenousvillage',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='indigenousvillage_ethnic_groups_layers', to='boundaries.City', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='indigenousvillage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indigenousvillage_ethnic_groups_layers', to='boundaries.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='indigenousvillage',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='indigenousvillage_ethnic_groups_layers', to='boundaries.State', verbose_name='States'),
        ),
    ]
