# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
